from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
def send(Text):
    strFrom = 'Review Snail<snail@reviewsnail.com>'
    strTo = ['senliksefa@gmail.com','metin.sehim@gmail.com','mcanaltintas1@gmail.com','korhanozdemir90@gmail.com']
    #strTo='kologluege@gmail.com'
    msgRoot = MIMEMultipart('related')
    """msgRoot['Subject'] = "Review Snail'in Kapalı Beta Programına Davet Edildiniz! """
    msgRoot['Subject'] = "Review Snail'in Kapalı Beta Programına Davet Edildiniz! "
    msgRoot['From'] = strFrom
    msgRoot['To'] = ",".join(strTo)

    msgAlternative = MIMEMultipart('alternative')
    msgRoot.attach(msgAlternative)

    msgText = MIMEText(Text,'html')
    msgAlternative.attach(msgText)

    ust_fp = open('/home/ReviewDetectorbot/.local/mail/Logo.png', 'rb')
    msgust = MIMEImage(ust_fp.read())
    ust_fp.close()
    msgust.add_header('Content-ID', '<ust>')
    msgRoot.attach(msgust)
    orta2_fp = open('/home/ReviewDetectorbot/.local/mail/Soru.png', 'rb')
    msgorta2 = MIMEImage(orta2_fp.read())
    orta2_fp.close()
    msgorta2.add_header('Content-ID', '<orta2>')
    msgRoot.attach(msgorta2)

    import smtplib
    smtp = smtplib.SMTP('smtp.zoho.com',587)
    smtp.starttls()
    smtp.login('snail@reviewsnail.com', '1928374655Snail__')
    smtp.sendmail(strFrom, strTo, msgRoot.as_string())
    smtp.quit()


text ='<body>    <div id="main" style="width: 900px;margin: auto;">        <div id="upper" class="tcenter" style="text-align: center;margin-top: 60px;margin-bottom: 50px;">            <img id="logo" class="" src="cid:ust" alt="" style="vertical-align: middle;padding-right: 35px;">            <span class="font bold header inline " style="display: inline-block;font-family: &quot;Roboto&quot;;font-weight: 400;font-size: 32pt;">Merhabalar</span></div>                <div id="text2" class="font midtext" style="font-family: &quot;Roboto&quot;;font-size: 14pt;width: 95%;margin-left: 55px;margin-top: 30px;">            <p class="midtext head" style="font-size: 16pt;width: 95%;font-weight: 500;">İstediğiniz Amazon çözümleri <b>Pahalı</b>, <b>Karmaşık</b> ve <b>Uğraştıcı</b> mı? </p>            <p class="midtext " style="font-size: 14pt;width: 95%;">                                 Amazon puanınızı yüksek tutmak mı istiyorsunuz? <br>                Düşük yıldızlı yorumlardan bir an önce haberdar olup müşterinizin sorununu çözmelisiniz! <br><br> <i>Peki onlarca ürünün yorum sayfasını nasıl takip edeceksiniz?</i><br>İşte bu noktada <span class="rocksalt" style="font-family: &quot;Rock salt&quot;;"> Review Snail </span> size aradığınız çözümü sunuyor! <br> Satışını yaptığınız herhangi bir ürüne yorum yapıldığında <span class="rocksalt" style="font-family: &quot;Rock salt&quot;;"> Review Snail </span> sizi <b>anında</b> bir bilgilendirme maili ile güncel tutsun! <br> <br> Üstelik kapalı beta süreci boyunca <b>Ücretsiz</b> ve daha sonrasında ise sadece <b>34.90 Tl</b>\'dan başlayan fiyatlarla! <br>            Review Snail\'e sadece bir kere kaydolun ve yapılan her yorumdan <b>anında</b> haberiniz olsun! <br>                       </p>        </div>        <div id="midlogo" class="tcenter" style="text-align: center;">            <img src="cid:orta2" alt="">        </div>         <div id="" class="">            <form action="www.reviewsnail.com">        <button id="button" style="margin: auto;display: block;margin-top: 30px;color: white;font-size: 30pt;font-family: &quot;roboto&quot;;background-color: #2af433;border: none;width: 150px;height: 60px;border-radius: 25px;">Katıl</button>        </form>                     <p class="font" id="text2" style="font-family: &quot;Roboto&quot;;margin-left:55px; ">Detaylı Bilgi İçin: <br>-info@reviewsnail.com</p>                           </div>        <div id="footer" class="tcenter font" style="text-align: center;font-family: &quot;Roboto&quot;;color: darkgrey;margin-top: 30px;font-size: 10pt;">            <p>                Copyright Ⓒ ReviewSnail.com, 2019 <br> All Rights Reserved. <br>info@reviewsnail.com            </p>        </div>    </div>    </body>'
text2='<body>    <div id="main" style="width: 900px;margin: auto;">        <div id="upper" class="tcenter" style="text-align: center;margin-top: 60px;margin-bottom: 50px;">            <img id="logo" class="" src="cid:ust" alt="" style="vertical-align: middle;padding-right: 35px;">            <span class="font bold header inline " style="display: inline-block;font-family: &quot;Roboto&quot;;font-weight: 400;font-size: 32pt;color: #4652b5;">Merhabalar</span></div> <br>               <div id="text2" class="font midtext" style="font-family: &quot;Roboto&quot;;font-size: 14pt;width: 80%;margin-top: 30px;margin: auto;">            <p class=" head tcenter" style="text-align: center;font-size: 26pt;font-weight: 550;color: #4652b5;">İstediğiniz Amazon çözümleri <b>Pahalı</b>, <br><b>Karmaşık</b> ve <b>Uğraştıcı</b> mı? </p>  <br>            <p class="midtext indent" style="font-size: 14pt;width: 95%;line-height:1.5;">                                 Amazon puanınızı yüksek tutmak mı istiyorsunuz? Düşük yıldızlı yorumlardan bir an önce haberdar olup müşterinizin sorununu çözmelisiniz!  <i>Peki onlarca ürünün yorum sayfasını nasıl takip edeceksiniz?</i> İşte bu noktada <b>Review Snail</b> size aradığınız çözümü sunuyor! <br><br> Satışını yaptığınız herhangi bir ürüne yorum yapıldığında <b>Review Snail </b> sizi bir bilgilendirme maili ile güncel tutsun! Üstelik kapalı beta süreci boyunca <b>Ücretsiz</b> ve daha sonrasında ise sadece <b>34.90 Tl</b>\'dan başlayan fiyatlarla!            Review Snail\'e sadece bir kere kaydolun ve yapılan her yorumdan <u>anında</u> haberdar olun! <br><br></p>                               </div>        <div id="midlogo" class="tcenter" style="text-align: center;">            <img src="cid:orta2" alt="">        </div><br><br>         <div id="" class="">                 <a id="button" href="www.reviewsnail.com" style="margin: auto;padding-top:10px;text-align:center;text-decoration:none; display: block;;color: white;font-size: 30pt;font-family: &quot;roboto&quot;;background-color: #2af433;border: none;width: 150px;height: 60px;border-radius: 25px;">Katıl</a> <br><br><br>                  <p class="font" id="text2" style="font-family: &quot;Roboto&quot;;width:80%;margin:auto;padding-top:30px">Detaylı Bilgi İçin: <br>-info@reviewsnail.com</p>                           </div>        <div id="footer" class="tcenter font" style="text-align: center;font-family: &quot;Roboto&quot;;color: darkgrey;margin-top: 30px;font-size: 10pt;">            <p>                Copyright Ⓒ ReviewSnail.com, 2019 <br> All Rights Reserved. <br>info@reviewsnail.com            </p>        </div>    </div>    </body>'
texting ='<body>    <div id="main" style="width: 900px;margin: auto;">        <div id="upper" class="tcenter" style="text-align: center;margin-top: 60px;margin-bottom: 50px;">            <img id="logo" class="" src="cid:ust" alt="" style="vertical-align: middle;padding-right: 35px;">            <span class="font bold header inline " style="display: inline-block;font-family: &quot;Roboto&quot;;font-weight: 400;font-size: 32pt;color: #4652b5;">Hey There !</span></div>                <div id="text2" class="font midtext" style="font-family: &quot;Roboto&quot;;font-size: 14pt;width: 95%;margin-left: 55px;margin-top: 30px;">            <p class="midtext head" style="font-size: 16pt;width: 95%;font-weight: 500;color: #4652b5;">Do you <b>struggle</b> to follow reviews left for your products in Amazon? Is it <b>frustrating</b> and <b>time consuming</b> to keep track of all? </p>            <p class="midtext " style="font-size: 14pt;width: 95%;">  <br><br><br> Then <span class="rocksalt" style="font-family: &quot;Rock salt&quot;;"> Review Snail </span> is the best monitoring solution for your Amazon business. <br> Join <span class="rocksalt" style="font-family: &quot;Rock salt&quot;;"> Review Snail </span> and get <b> notifications </b> via pretty e-mails like this one when a review is left on your product.! <br> <br> Closed-Beta has just started. Join today and get our services <b> FREE </b> After that our prices start from just <b>5.99$</b> . <br>Join Review Snail Now and start boosting your seller points <b> IMMEDIATELY </b>.</p>        </div>        <div id="midlogo" class="tcenter" style="text-align: center;">            <img src="cid:orta2" alt="">        </div>         <div id="" class="">            <form action="www.reviewsnail.com">        <button id="button" style="margin: auto;display: block;margin-top: 30px;color: white;font-size: 30pt;font-family: &quot;roboto&quot;;background-color: #2af433;border: none;width: 150px;height: 60px;border-radius: 25px;">Join</button>        </form>                     <p class="font" id="text2" style="font-family: &quot;Roboto&quot;;margin-left:55px; ">Detaylı Bilgi İçin: <br>-info@reviewsnail.com</p>                           </div>        <div id="footer" class="tcenter font" style="text-align: center;font-family: &quot;Roboto&quot;;color: darkgrey;margin-top: 30px;font-size: 10pt;">            <p>                Copyright Ⓒ ReviewSnail.com, 2019 <br> All Rights Reserved. <br>info@reviewsnail.com            </p>        </div>    </div>    </body>'
send(texting)



